# Generated by Django 5.2.7 on 2025-11-10 19:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLogAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glosa', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Acción de log',
                'verbose_name_plural': 'Acciones de log',
                'db_table': 'auth_log_accion',
            },
        ),
        migrations.CreateModel(
            name='AuthEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glosa', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de usuario',
                'verbose_name_plural': 'Estados de usuario',
                'db_table': 'auth_estado',
                'indexes': [models.Index(fields=['activo'], name='auth_estado_activo_e0b41a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('agente', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='accounts.authlogaccion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de autenticación',
                'verbose_name_plural': 'Logs de autenticación',
                'db_table': 'auth_logs',
                'indexes': [models.Index(fields=['usuario'], name='auth_logs_usuario_15447e_idx'), models.Index(fields=['accion'], name='auth_logs_accion__2815c8_idx'), models.Index(fields=['-fecha_creacion'], name='auth_logs_fecha_c_1b6d74_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthUserEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='accounts.authestado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado asignado a usuario',
                'verbose_name_plural': 'Estados de usuarios',
                'db_table': 'auth_user_estado',
                'indexes': [models.Index(fields=['usuario'], name='auth_user_e_usuario_92158f_idx'), models.Index(fields=['estado'], name='auth_user_e_estado__3ab1ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario',), name='uq_auth_user_estado_user_single')],
            },
        ),
        migrations.CreateModel(
            name='HistorialLogin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, help_text='Clave de sesión (session_key). Si existe, puede relacionarse con sesiones_usuarios.id', max_length=128, null=True, verbose_name='clave_sesión')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('agente', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('fecha_login', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha_login')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de login',
                'verbose_name_plural': 'Historiales de login',
                'db_table': 'auth_user_login_history',
                'ordering': ['-fecha_login'],
                'indexes': [models.Index(fields=['usuario', 'fecha_login'], name='ix_login_usuario_fecha'), models.Index(fields=['session_key'], name='ix_login_session_key'), models.Index(fields=['direccion_ip', 'fecha_login'], name='ix_login_ip_fecha')],
            },
        ),
    ]
