# Generated by Django 5.2.7 on 2025-12-07 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(help_text='Código único del cargo (ej: PROF-MAT, BOD-001)', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del cargo', max_length=100, verbose_name='Nombre del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'tba_cargos',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='tba_cargos_codigo_eee2ee_idx'), models.Index(fields=['activo', 'eliminado'], name='tba_cargos_activo_d9e60f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('accion', models.CharField(choices=[('CONFIRMACION_ENTREGA', 'Confirmación de Entrega'), ('INTENTO_FALLIDO', 'Intento Fallido'), ('BLOQUEO', 'Bloqueo de Usuario'), ('DESBLOQUEO', 'Desbloqueo de Usuario')], max_length=50, verbose_name='Acción')),
                ('exitoso', models.BooleanField(verbose_name='Exitoso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('detalles', models.JSONField(blank=True, help_text='Información adicional en formato JSON', null=True, verbose_name='Detalles Adicionales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_pin', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de PIN',
                'verbose_name_plural': 'Auditorías de PIN',
                'db_table': 'tba_auditoria_pin',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='tba_auditor_usuario_237381_idx'), models.Index(fields=['accion'], name='tba_auditor_accion_5c510c_idx'), models.Index(fields=['exitoso'], name='tba_auditor_exitoso_0f251f_idx'), models.Index(fields=['activo', 'eliminado'], name='tba_auditor_activo_e26d3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('documento_identidad', models.CharField(help_text='RUT chileno o documento de identidad', max_length=20, unique=True, verbose_name='RUT/Documento de Identidad')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido1', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Apellido')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('talla', models.CharField(blank=True, help_text='Talla de ropa (XS, S, M, L, XL, XXL)', max_length=10, null=True, verbose_name='Talla')),
                ('numero_zapato', models.CharField(blank=True, help_text='Número de zapato para EPP', max_length=5, null=True, verbose_name='Número de Zapato')),
                ('user', models.OneToOneField(help_text='Usuario asociado a esta persona', on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Persona/Funcionario',
                'verbose_name_plural': 'Personas/Funcionarios',
                'db_table': 'tba_persona',
                'ordering': ['apellido1', 'apellido2', 'nombres'],
                'indexes': [models.Index(fields=['documento_identidad'], name='tba_persona_documen_dbd769_idx'), models.Index(fields=['user'], name='tba_persona_user_id_344548_idx'), models.Index(fields=['activo', 'eliminado'], name='tba_persona_activo_9074e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar vacío si es el cargo actual', null=True, verbose_name='Fecha de Fin')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='accounts.cargo', verbose_name='Cargo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_historico', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cargo de Usuario',
                'verbose_name_plural': 'Cargos de Usuarios',
                'db_table': 'tba_user_cargos',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['usuario', 'fecha_inicio'], name='tba_user_ca_usuario_3528f9_idx'), models.Index(fields=['cargo'], name='tba_user_ca_cargo_i_235856_idx'), models.Index(fields=['activo', 'eliminado'], name='tba_user_ca_activo_775366_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSecure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('pin', models.CharField(help_text='PIN de 4 dígitos (almacenado encriptado)', max_length=255, verbose_name='PIN Encriptado')),
                ('intentos_fallidos', models.IntegerField(default=0, verbose_name='Intentos Fallidos')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Usuario Bloqueado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguridad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguridad de Usuario',
                'verbose_name_plural': 'Seguridad de Usuarios',
                'db_table': 'tba_user_secure',
                'indexes': [models.Index(fields=['user'], name='tba_user_se_user_id_21f537_idx'), models.Index(fields=['bloqueado'], name='tba_user_se_bloquea_3d2d85_idx'), models.Index(fields=['activo', 'eliminado'], name='tba_user_se_activo_37b324_idx')],
            },
        ),
    ]
