# Generated by Django 5.2.7 on 2026-02-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_persona_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoriapin',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='auditoriapin',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='usercargo',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='usercargo',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='usersecure',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='usersecure',
            name='usuario_creacion',
        ),
        migrations.AddField(
            model_name='persona',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
    ]
