# Generated by Django 5.2.7 on 2026-03-13 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_auditoriapin_usuario_actualizacion_and_more'),
        ('bodega', '0011_remove_articulo_usuario_actualizacion_and_more'),
        ('solicitudes', '0010_remove_area_usuario_actualizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('scope_level', models.CharField(choices=[('GLOBAL', 'Global'), ('DEPARTAMENTO', 'Departamento'), ('AREA', 'Area'), ('BODEGA', 'Bodega'), ('OWN', 'Propio')], default='OWN', help_text='Define si el usuario ve todo, su departamento, su área, su bodega o solo lo propio.', max_length=20, verbose_name='Nivel de alcance')),
                ('puede_aprobar_propias', models.BooleanField(default=False, help_text='Excepción de alto riesgo. Mantener en False salvo caso formalmente aprobado.', verbose_name='Puede aprobar propias')),
                ('puede_administrar_autorizacion', models.BooleanField(default=False, help_text='Permite gestionar roles oficiales y perfiles de acceso.', verbose_name='Puede administrar autorización')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_con_acceso', to='solicitudes.area', verbose_name='Area de alcance')),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_con_acceso', to='bodega.bodega', verbose_name='Bodega de alcance')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_con_acceso', to='solicitudes.departamento', verbose_name='Departamento de alcance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de acceso',
                'verbose_name_plural': 'Perfiles de acceso',
                'db_table': 'tba_user_access_profile',
                'permissions': [('manage_access_profiles', 'Puede administrar perfiles de acceso'), ('view_all_auditoria', 'Puede ver auditoría global'), ('export_sensitive_reports', 'Puede exportar reportes sensibles')],
                'indexes': [models.Index(fields=['user'], name='tba_user_ac_user_id_53eab6_idx'), models.Index(fields=['scope_level'], name='tba_user_ac_scope_l_c30711_idx'), models.Index(fields=['departamento'], name='tba_user_ac_departa_5a5aa2_idx'), models.Index(fields=['area'], name='tba_user_ac_area_id_8d0d7c_idx'), models.Index(fields=['bodega'], name='tba_user_ac_bodega__2eec7e_idx'), models.Index(fields=['activo', 'eliminado'], name='tba_user_ac_activo_a98090_idx')],
            },
        ),
    ]
