# Generated by Django 5.1.6 on 2026-04-06 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraccessprofile'),
        ('solicitudes', '0010_remove_area_usuario_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento principal al que pertenece el funcionario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='solicitudes.departamento', verbose_name='Departamento'),
        ),
    ]
