# Generated by Django 5.2.7 on 2025-11-11 09:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0002_initial'),
        ('bodega', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(help_text='Código único del departamento', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del departamento', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del departamento', null=True, verbose_name='Descripción')),
                ('responsable', models.ForeignKey(blank=True, help_text='Usuario responsable del departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'tba_solicitudes_conf_departamento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(help_text='Código único del área', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del área', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del área', null=True, verbose_name='Descripción')),
                ('responsable', models.ForeignKey(blank=True, help_text='Usuario responsable del área', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('departamento', models.ForeignKey(help_text='Departamento al que pertenece el área', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='solicitudes.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'tba_solicitudes_conf_area',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(help_text='Código único del equipo', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del equipo', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del equipo', null=True, verbose_name='Descripción')),
                ('departamento', models.ForeignKey(help_text='Departamento al que pertenece el equipo', on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='solicitudes.departamento', verbose_name='Departamento')),
                ('lider', models.ForeignKey(blank=True, help_text='Usuario líder del equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_lider', to=settings.AUTH_USER_MODEL, verbose_name='Líder')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'tba_solicitudes_conf_equipo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(help_text='Código único del estado', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del estado', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del estado', null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#6c757d', help_text='Color hexadecimal para representación visual', max_length=7, verbose_name='Color (Hex)')),
                ('es_inicial', models.BooleanField(default=False, help_text='Indica si es un estado inicial', verbose_name='Estado Inicial')),
                ('es_final', models.BooleanField(default=False, help_text='Indica si es un estado final', verbose_name='Estado Final')),
                ('requiere_accion', models.BooleanField(default=False, help_text='Indica si el estado requiere acción del usuario', verbose_name='Requiere Acción')),
            ],
            options={
                'verbose_name': 'Estado de Solicitud',
                'verbose_name_plural': 'Estados de Solicitudes',
                'db_table': 'tba_solicitudes_conf_estado',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='tba_solicit_codigo_f04e03_idx'), models.Index(fields=['es_inicial'], name='tba_solicit_es_inic_d58fc0_idx'), models.Index(fields=['es_final'], name='tba_solicit_es_fina_d00e84_idx'), models.Index(fields=['activo', 'eliminado'], name='tba_solicit_activo_7a9eef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Solicitud de Activos/Bienes'), ('ARTICULO', 'Solicitud de Artículos')], default='ARTICULO', help_text='Define si la solicitud es de activos (bienes) o artículos', max_length=10, verbose_name='Tipo')),
                ('numero', models.CharField(help_text='Número único de la solicitud', max_length=20, unique=True, verbose_name='Número de Solicitud')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la solicitud', verbose_name='Fecha de Solicitud')),
                ('fecha_requerida', models.DateField(help_text='Fecha en que se requieren los materiales', verbose_name='Fecha Requerida')),
                ('titulo_actividad', models.CharField(blank=True, help_text='Título descriptivo de la actividad para la cual se solicitan los materiales', max_length=200, null=True, verbose_name='Título de la Actividad')),
                ('objetivo_actividad', models.TextField(blank=True, help_text='Objetivo que se busca alcanzar con esta actividad', null=True, verbose_name='Objetivo de la Actividad')),
                ('area_solicitante', models.CharField(help_text='Nombre del área que solicita', max_length=100, verbose_name='Área Solicitante')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, help_text='Fecha y hora de aprobación', null=True, verbose_name='Fecha de Aprobación')),
                ('fecha_despacho', models.DateTimeField(blank=True, help_text='Fecha y hora de despacho', null=True, verbose_name='Fecha de Despacho')),
                ('motivo', models.TextField(help_text='Justificación de la solicitud', verbose_name='Motivo de la Solicitud')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales', null=True, verbose_name='Observaciones')),
                ('notas_aprobacion', models.TextField(blank=True, help_text='Notas del aprobador', null=True, verbose_name='Notas de Aprobación')),
                ('notas_despacho', models.TextField(blank=True, help_text='Notas del despachador', null=True, verbose_name='Notas de Despacho')),
                ('aprobador', models.ForeignKey(blank=True, help_text='Usuario que aprobó la solicitud', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobador')),
                ('area', models.ForeignKey(blank=True, help_text='Área asociada a la solicitud', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.area', verbose_name='Área')),
                ('bodega_origen', models.ForeignKey(blank=True, help_text='Solo requerido para solicitudes de artículos. Las solicitudes de activos no tienen bodega.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_origen', to='bodega.bodega', verbose_name='Bodega Origen')),
                ('departamento', models.ForeignKey(blank=True, help_text='Departamento asociado a la solicitud', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.departamento', verbose_name='Departamento')),
                ('despachador', models.ForeignKey(blank=True, help_text='Usuario que despachó la solicitud', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_despachadas', to=settings.AUTH_USER_MODEL, verbose_name='Despachador')),
                ('equipo', models.ForeignKey(blank=True, help_text='Equipo asociado a la solicitud', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.equipo', verbose_name='Equipo')),
                ('estado', models.ForeignKey(help_text='Estado actual de la solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.estadosolicitud', verbose_name='Estado')),
                ('solicitante', models.ForeignKey(help_text='Usuario que realiza la solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'tba_solicitudes_solicitud',
                'ordering': ['-fecha_solicitud', '-numero'],
                'permissions': [('aprobar_solicitud', 'Puede aprobar solicitudes'), ('rechazar_solicitud', 'Puede rechazar solicitudes'), ('despachar_solicitud', 'Puede despachar solicitudes'), ('change_any_solicitud', 'Puede editar cualquier solicitud'), ('delete_any_solicitud', 'Puede eliminar cualquier solicitud'), ('ver_todas_solicitudes', 'Puede ver todas las solicitudes')],
            },
        ),
        migrations.CreateModel(
            name='HistorialSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre el cambio de estado', null=True, verbose_name='Observaciones')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del cambio de estado', verbose_name='Fecha de Cambio')),
                ('estado_anterior', models.ForeignKey(blank=True, help_text='Estado previo al cambio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_anterior', to='solicitudes.estadosolicitud', verbose_name='Estado Anterior')),
                ('estado_nuevo', models.ForeignKey(help_text='Estado resultante del cambio', on_delete=django.db.models.deletion.PROTECT, related_name='historiales_nuevo', to='solicitudes.estadosolicitud', verbose_name='Estado Nuevo')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el cambio de estado', on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_solicitud', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('solicitud', models.ForeignKey(help_text='Solicitud a la que pertenece el registro', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Historial de Solicitud',
                'verbose_name_plural': 'Historial de Solicitudes',
                'db_table': 'tba_solicitudes_historial',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, help_text='Cantidad solicitada del artículo o activo', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad Solicitada')),
                ('cantidad_aprobada', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad aprobada por el aprobador', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Aprobada')),
                ('cantidad_despachada', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad efectivamente despachada', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Despachada')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones específicas del detalle', null=True, verbose_name='Observaciones')),
                ('activo', models.ForeignKey(blank=True, help_text='Bien o activo solicitado (solo para solicitudes de activos)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_solicitud', to='activos.activo', verbose_name='Bien/Activo')),
                ('articulo', models.ForeignKey(blank=True, help_text='Artículo solicitado (solo para solicitudes de artículos)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_solicitud', to='bodega.articulo', verbose_name='Artículo')),
                ('solicitud', models.ForeignKey(help_text='Solicitud a la que pertenece el detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitudes',
                'db_table': 'tba_solicitudes_detalle',
                'ordering': ['solicitud', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(help_text='Código único del tipo de solicitud', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tipo', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del tipo', null=True, verbose_name='Descripción')),
                ('requiere_aprobacion', models.BooleanField(default=True, help_text='Indica si las solicitudes de este tipo requieren aprobación', verbose_name='Requiere Aprobación')),
            ],
            options={
                'verbose_name': 'Tipo de Solicitud',
                'verbose_name_plural': 'Tipos de Solicitud',
                'db_table': 'tba_solicitudes_conf_tipo',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='tba_solicit_codigo_fac609_idx'), models.Index(fields=['activo', 'eliminado'], name='tba_solicit_activo_c4b785_idx')],
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_solicitud',
            field=models.ForeignKey(help_text='Tipo de solicitud según catálogo', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='solicitudes.tiposolicitud', verbose_name='Tipo de Solicitud'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['codigo'], name='tba_solicit_codigo_d9645f_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['activo', 'eliminado'], name='tba_solicit_activo_7bd44a_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['codigo'], name='tba_solicit_codigo_e0ec03_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['departamento'], name='tba_solicit_departa_67f861_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['activo', 'eliminado'], name='tba_solicit_activo_9ebc34_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['codigo'], name='tba_solicit_codigo_721772_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['departamento'], name='tba_solicit_departa_1f1848_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['activo', 'eliminado'], name='tba_solicit_activo_3e052a_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitud',
            index=models.Index(fields=['solicitud'], name='tba_solicit_solicit_abc341_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitud',
            index=models.Index(fields=['fecha_cambio'], name='tba_solicit_fecha_c_03f479_idx'),
        ),
        migrations.AddIndex(
            model_name='historialsolicitud',
            index=models.Index(fields=['usuario'], name='tba_solicit_usuario_1113df_idx'),
        ),
        migrations.AddIndex(
            model_name='detallesolicitud',
            index=models.Index(fields=['solicitud'], name='tba_solicit_solicit_959ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='detallesolicitud',
            index=models.Index(fields=['articulo'], name='tba_solicit_articul_f8f610_idx'),
        ),
        migrations.AddIndex(
            model_name='detallesolicitud',
            index=models.Index(fields=['activo'], name='tba_solicit_activo__18be64_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['numero'], name='tba_solicit_numero_1d2d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['tipo'], name='tba_solicit_tipo_77da04_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['fecha_solicitud'], name='tba_solicit_fecha_s_b27307_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['fecha_requerida'], name='tba_solicit_fecha_r_b35267_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['solicitante'], name='tba_solicit_solicit_ef8e58_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado'], name='tba_solicit_estado__e84001_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['tipo_solicitud'], name='tba_solicit_tipo_so_8e215f_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['activo', 'eliminado'], name='tba_solicit_activo_642a18_idx'),
        ),
    ]
