# Generated by Django 5.2.7 on 2025-11-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='area_solicitante',
            field=models.CharField(blank=True, help_text='Campo deprecado - usar estructura organizacional (area)', max_length=100, null=True, verbose_name='Área Solicitante (Deprecado)'),
        ),
    ]
