# Generated by Django 5.2.7 on 2025-11-29 14:50

from django.db import migrations


def add_missing_columns(apps, schema_editor):
    """
    Agrega las columnas departamento_id y area_id si no existen.
    """
    with schema_editor.connection.cursor() as cursor:
        # Verificar y agregar departamento_id
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='tba_solicitudes_solicitud'
            AND column_name='departamento_id'
        """)
        if cursor.fetchone() is None:
            cursor.execute("""
                ALTER TABLE tba_solicitudes_solicitud
                ADD COLUMN departamento_id BIGINT NULL
                REFERENCES tba_solicitudes_conf_departamento(id)
                DEFERRABLE INITIALLY DEFERRED
            """)
            cursor.execute("""
                CREATE INDEX tba_solicitudes_solicitud_departamento_id_idx
                ON tba_solicitudes_solicitud(departamento_id)
            """)

        # Verificar y agregar area_id
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='tba_solicitudes_solicitud'
            AND column_name='area_id'
        """)
        if cursor.fetchone() is None:
            cursor.execute("""
                ALTER TABLE tba_solicitudes_solicitud
                ADD COLUMN area_id BIGINT NULL
                REFERENCES tba_solicitudes_conf_area(id)
                DEFERRABLE INITIALLY DEFERRED
            """)
            cursor.execute("""
                CREATE INDEX tba_solicitudes_solicitud_area_id_idx
                ON tba_solicitudes_solicitud(area_id)
            """)


def remove_columns(apps, schema_editor):
    """
    Elimina las columnas departamento_id y area_id.
    """
    with schema_editor.connection.cursor() as cursor:
        for column in ['departamento_id', 'area_id']:
            cursor.execute(f"""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name='tba_solicitudes_solicitud'
                AND column_name='{column}'
            """)
            if cursor.fetchone() is not None:
                cursor.execute(f"""
                    ALTER TABLE tba_solicitudes_solicitud
                    DROP COLUMN {column}
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_missing_columns, remove_columns),
    ]
