# Generated by Django 5.2.7 on 2025-11-27 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitud_area_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='area_solicitante',
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='cantidad_aprobada',
            field=models.IntegerField(default=0, help_text='Cantidad aprobada por el aprobador', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Aprobada'),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='cantidad_despachada',
            field=models.IntegerField(default=0, help_text='Cantidad efectivamente despachada', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Despachada'),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='cantidad_solicitada',
            field=models.IntegerField(help_text='Cantidad solicitada del artículo o activo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Solicitada'),
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
