# Generated by Django 5.2.7 on 2025-11-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_add_missing_fk_columns'),
        ('solicitudes', '0003_remove_solicitud_equipo_and_more'),
    ]

    operations = [
    ]
