# Generated by Django 5.2.7 on 2025-12-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_merge_20251129_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_solicitud', '-numero'], 'permissions': [('gestionar_solicitudes', 'Gestión: Puede administrar completamente el módulo de solicitudes'), ('aprobar_solicitudes', 'Gestión: Puede aprobar solicitudes pendientes de aprobación'), ('rechazar_solicitudes', 'Gestión: Puede rechazar solicitudes y agregar observaciones'), ('despachar_solicitudes', 'Gestión: Puede despachar solicitudes aprobadas y registrar entregas'), ('ver_todas_solicitudes', 'Gestión: Puede visualizar todas las solicitudes del sistema'), ('editar_cualquier_solicitud', 'Gestión: Puede editar cualquier solicitud independiente del estado o solicitante'), ('eliminar_cualquier_solicitud', 'Gestión: Puede eliminar cualquier solicitud independiente del estado o solicitante'), ('crear_solicitud_articulos', 'Solicitud Artículos: Puede crear nuevas solicitudes de artículos de bodega'), ('ver_solicitudes_articulos', 'Solicitud Artículos: Puede ver todas las solicitudes de artículos del sistema'), ('crear_solicitud_bienes', 'Solicitud Bienes: Puede crear nuevas solicitudes de bienes/activos de inventario'), ('ver_solicitudes_bienes', 'Solicitud Bienes: Puede ver todas las solicitudes de bienes/activos del sistema'), ('ver_mis_solicitudes', 'Mis Solicitudes: Puede ver sus propias solicitudes creadas'), ('editar_mis_solicitudes', 'Mis Solicitudes: Puede editar sus propias solicitudes en estado borrador o pendiente'), ('eliminar_mis_solicitudes', 'Mis Solicitudes: Puede eliminar sus propias solicitudes en estado borrador')], 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
    ]
