# Generated by Django 5.2.7 on 2025-12-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_reorganizar_permisos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_solicitud', '-numero'], 'permissions': [('gestionar_solicitudes', 'Puede administrar completamente el módulo de solicitudes'), ('aprobar_solicitudes', 'Puede aprobar solicitudes pendientes de aprobación'), ('rechazar_solicitudes', 'Puede rechazar solicitudes y agregar observaciones'), ('despachar_solicitudes', 'Puede despachar solicitudes aprobadas y registrar entregas'), ('ver_todas_solicitudes', 'Puede visualizar todas las solicitudes del sistema'), ('editar_cualquier_solicitud', 'Puede editar cualquier solicitud independiente del estado o solicitante'), ('eliminar_cualquier_solicitud', 'Puede eliminar cualquier solicitud independiente del estado o solicitante'), ('crear_solicitud_articulos', 'Puede crear nuevas solicitudes de artículos de bodega'), ('ver_solicitudes_articulos', 'Puede ver todas las solicitudes de artículos del sistema'), ('crear_solicitud_bienes', 'Puede crear nuevas solicitudes de bienes/activos de inventario'), ('ver_solicitudes_bienes', 'Puede ver todas las solicitudes de bienes/activos del sistema'), ('ver_mis_solicitudes', 'Puede ver sus propias solicitudes creadas'), ('editar_mis_solicitudes', 'Puede editar sus propias solicitudes en estado borrador o pendiente'), ('eliminar_mis_solicitudes', 'Puede eliminar sus propias solicitudes en estado borrador')], 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
    ]
