# Generated by Django 5.2.7 on 2025-12-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('solicitudes', '0006_actualizar_descripciones_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPermiso',
            fields=[
                ('permiso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='categoria', serialize=False, to='auth.permission', verbose_name='Permiso')),
                ('modulo', models.CharField(choices=[('GESTION', 'Gestión'), ('SOLICITUD_ARTICULOS', 'Solicitud Artículos'), ('SOLICITUD_BIENES', 'Solicitud Bienes'), ('MIS_SOLICITUDES', 'Mis Solicitudes')], db_index=True, help_text='Módulo funcional al que pertenece el permiso', max_length=50, verbose_name='Módulo')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de visualización dentro del módulo', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de Permiso',
                'verbose_name_plural': 'Categorías de Permisos',
                'db_table': 'tba_solicitudes_categoria_permiso',
                'ordering': ['modulo', 'orden'],
                'indexes': [models.Index(fields=['modulo', 'orden'], name='tba_solicit_modulo_3b1289_idx')],
            },
        ),
    ]
