# Generated by Django 5.2.7 on 2025-12-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_agregar_categoria_permiso'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='categoriapermiso',
            new_name='tba_solicit_modulo_3b20d9_idx',
            old_name='tba_solicit_modulo_3b1289_idx',
        ),
        migrations.AlterField(
            model_name='categoriapermiso',
            name='modulo',
            field=models.CharField(choices=[('GESTION', 'Gestión'), ('SOLICITUD_ARTICULOS', 'Solicitud Artículos'), ('SOLICITUD_BIENES', 'Solicitud Bienes'), ('MIS_SOLICITUDES', 'Mis Solicitudes'), ('MANTENEDORES', 'Mantenedores')], db_index=True, help_text='Módulo funcional al que pertenece el permiso', max_length=50, verbose_name='Módulo'),
        ),
        migrations.AlterModelTable(
            name='categoriapermiso',
            table='tba_solicitudes_permiso',
        ),
    ]
