# Generated by Django 5.2.7 on 2025-12-07 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_rename_tba_solicit_modulo_3b1289_idx_tba_solicit_modulo_3b20d9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='area',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='estadosolicitud',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='estadosolicitud',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='historialsolicitud',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='historialsolicitud',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='tiposolicitud',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='tiposolicitud',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
    ]
