# Generated by Django 5.2.7 on 2026-02-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_area_usuario_actualizacion_area_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='area',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='detallesolicitud',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='detallesolicitud',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='estadosolicitud',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='estadosolicitud',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='historialsolicitud',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='historialsolicitud',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='tiposolicitud',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='tiposolicitud',
            name='usuario_creacion',
        ),
    ]
