# Generated by Django 5.2.7 on 2025-11-11 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('bajas_inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoactivo',
            name='id_baja_inventario',
            field=models.ForeignKey(blank=True, help_text='ID de la baja de inventario asociada, si aplica', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_activo', to='bajas_inventario.bajainventario', verbose_name='ID Baja de Inventario'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable del activo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='proveniencia',
            field=models.ForeignKey(blank=True, help_text='Origen o procedencia del activo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='activos.proveniencia', verbose_name='Proveniencia'),
        ),
        migrations.AddField(
            model_name='taller',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Persona responsable del taller', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talleres_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='taller',
            field=models.ForeignKey(blank=True, help_text='Taller asociado al movimiento, si aplica', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_taller', to='activos.taller', verbose_name='Taller'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='tipo_movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='activos.tipomovimientoactivo', verbose_name='Tipo de Movimiento'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, help_text='Ubicación física donde se encuentra el activo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='activos.ubicacion', verbose_name='Ubicación Destino'),
        ),
    ]
