# Generated by Django 5.2.7 on 2025-11-16 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_add_sigla_to_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoactivo',
            name='estado_nuevo',
            field=models.ForeignKey(blank=True, help_text='Estado al que se cambiará el activo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_estado', to='activos.estadoactivo', verbose_name='Nuevo Estado'),
        ),
        migrations.AlterField(
            model_name='movimientoactivo',
            name='tipo_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='activos.tipomovimientoactivo', verbose_name='Tipo de Movimiento'),
        ),
    ]
