# Generated by Django 5.2.7 on 2025-12-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_activo_usuario_actualizacion_activo_usuario_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoactivo',
            name='confirmado_con_pin',
            field=models.BooleanField(default=False, help_text='Indica si el movimiento fue confirmado con PIN del responsable', verbose_name='Confirmado con PIN'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='fecha_confirmacion_pin',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se confirmó el movimiento con PIN', null=True, verbose_name='Fecha de Confirmación PIN'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='ip_confirmacion',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se confirmó el movimiento', null=True, verbose_name='IP de Confirmación'),
        ),
    ]
