# Generated by Django 5.2.7 on 2026-02-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_agregar_campos_confirmacion_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='categoriaactivo',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='categoriaactivo',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='estadoactivo',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='estadoactivo',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='movimientoactivo',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='movimientoactivo',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='proveniencia',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='proveniencia',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='tipomovimientoactivo',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='tipomovimientoactivo',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='usuario_creacion',
        ),
    ]
