# Generated by Django 5.2.7 on 2026-03-04 00:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0010_remove_area_usuario_actualizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotocopiadoraEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=150, verbose_name='Ubicacion')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Equipo Fotocopiadora',
                'verbose_name_plural': 'Equipos Fotocopiadora',
                'db_table': 'tba_fotocopiadora_equipo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TrabajoFotocopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Numero')),
                ('fecha_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('tipo_uso', models.CharField(choices=[('INTERNO', 'Uso Interno'), ('PERSONAL', 'Uso Personal'), ('EXTERNO', 'Uso Externo')], max_length=20, verbose_name='Tipo de Uso')),
                ('solicitante_nombre', models.CharField(max_length=200, verbose_name='Solicitante')),
                ('rut_solicitante', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT Solicitante')),
                ('cantidad_copias', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Copias')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio Unitario')),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_fotocopia', to='solicitudes.area', verbose_name='Area')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajos_fotocopia', to='solicitudes.departamento', verbose_name='Departamento')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='fotocopiadora.fotocopiadoraequipo', verbose_name='Equipo')),
                ('solicitante_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_fotocopia', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante (Usuario)')),
            ],
            options={
                'verbose_name': 'Trabajo Fotocopia',
                'verbose_name_plural': 'Trabajos Fotocopia',
                'db_table': 'tba_fotocopiadora_trabajo',
                'ordering': ['-fecha_hora', '-numero'],
                'permissions': [('registrar_trabajo_interno', 'Puede registrar trabajo interno de fotocopiadora'), ('registrar_trabajo_cobro', 'Puede registrar trabajo con cobro informativo'), ('anular_trabajo_fotocopia', 'Puede anular trabajos de fotocopiadora'), ('ver_reportes_fotocopiadora', 'Puede ver reportes de fotocopiadora'), ('gestionar_equipos_fotocopiadora', 'Puede gestionar equipos de fotocopiadora')],
                'indexes': [models.Index(fields=['-fecha_hora'], name='tba_fotocop_fecha_h_79d11b_idx'), models.Index(fields=['tipo_uso', '-fecha_hora'], name='tba_fotocop_tipo_us_fd4403_idx'), models.Index(fields=['equipo', '-fecha_hora'], name='tba_fotocop_equipo__2ec17f_idx'), models.Index(fields=['rut_solicitante'], name='tba_fotocop_rut_sol_5701db_idx')],
            },
        ),
    ]
