# Generated by Django 5.2.7 on 2026-03-13 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotocopiadora', '0002_printcostcenter_printrequest_printrequestattachment_and_more'),
        ('solicitudes', '0010_remove_area_usuario_actualizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printrequest',
            options={'ordering': ['-fecha_creacion', '-required_at'], 'permissions': [('submit_printrequest', 'Puede enviar solicitudes de impresion'), ('approve_printrequest', 'Puede aprobar solicitudes de impresion'), ('reject_printrequest', 'Puede rechazar solicitudes de impresion'), ('partial_approve_printrequest', 'Puede aprobar parcialmente solicitudes de impresion'), ('operate_printrequest', 'Puede operar solicitudes de impresion'), ('assign_operator_printrequest', 'Puede asignar operador a solicitudes de impresion'), ('mark_ready_printrequest', 'Puede marcar solicitudes listas para retiro'), ('deliver_printrequest', 'Puede marcar solicitudes entregadas'), ('close_printrequest', 'Puede cerrar solicitudes de impresion'), ('cancel_own_printrequest', 'Puede cancelar sus propias solicitudes de impresion'), ('cancel_any_printrequest', 'Puede cancelar cualquier solicitud de impresion'), ('reopen_printrequest', 'Puede reabrir solicitudes de impresion'), ('view_all_printrequest', 'Puede ver todas las solicitudes de impresion'), ('view_department_printrequest', 'Puede ver solicitudes de impresion de su ambito'), ('view_operational_queue_printrequest', 'Puede ver la bandeja operativa de impresion'), ('manage_print_settings', 'Puede gestionar configuracion del modulo de impresion'), ('manage_print_cost_centers', 'Puede gestionar centros de costo y cuotas de impresion'), ('manage_print_memberships', 'Puede gestionar memberships del modulo de impresion')], 'verbose_name': 'Solicitud de impresion', 'verbose_name_plural': 'Solicitudes de impresion'},
        ),
        migrations.RemoveConstraint(
            model_name='printrolemembership',
            name='uniq_print_role_membership_scope',
        ),
        migrations.AddField(
            model_name='printrequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_requests_cancelled', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='close_reason',
            field=models.TextField(blank=True, verbose_name='Motivo de cierre'),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_requests_closed', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por'),
        ),
        migrations.AddField(
            model_name='printrolemembership',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_role_memberships', to='fotocopiadora.printcostcenter', verbose_name='Centro de costo'),
        ),
        migrations.AddField(
            model_name='printrolemembership',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Vigente desde'),
        ),
        migrations.AddField(
            model_name='printrolemembership',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='Vigente hasta'),
        ),
        migrations.AlterField(
            model_name='printrolemembership',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'Solicitante'), ('APPROVER', 'Aprobador'), ('OPERATOR', 'Operador'), ('ADMIN', 'Administrador'), ('AUDITOR', 'Auditor'), ('SUPERADMIN', 'Superadministrador')], max_length=30, verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='printrolemembership',
            index=models.Index(fields=['cost_center', 'role'], name='tba_print_r_cost_ce_8e11d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='printrolemembership',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'departamento', 'area', 'equipo', 'cost_center'), name='uniq_print_role_membership_scope'),
        ),
        migrations.AddConstraint(
            model_name='printrolemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('eliminado', False), ('is_primary', True)), fields=('user',), name='uniq_active_primary_print_membership_per_user'),
        ),
    ]
