# Generated by Django 5.1.6 on 2026-06-21 00:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotocopiadora', '0003_alter_printrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printrequest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto Total'),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='use_type',
            field=models.CharField(choices=[('INTERNO', 'Uso Institucional (Colegio)'), ('PERSONAL', 'Uso Personal (Docente)')], default='INTERNO', max_length=20, verbose_name='Tipo de uso'),
        ),
        migrations.AddField(
            model_name='printrequestitem',
            name='ring_bound',
            field=models.BooleanField(default=False, verbose_name='Anillado'),
        ),
        migrations.AlterField(
            model_name='printrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_APPROVAL', 'POR APROBAR'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('IN_PROGRESS', 'En preparacion'), ('READY_FOR_PICKUP', 'Lista para retiro'), ('DELIVERED', 'Entregada'), ('CLOSED', 'Cerrada'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='printrequestitem',
            name='original_page_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de paginas originales'),
        ),
        migrations.AlterField(
            model_name='printrequeststatushistory',
            name='to_status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_APPROVAL', 'POR APROBAR'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('IN_PROGRESS', 'En preparacion'), ('READY_FOR_PICKUP', 'Lista para retiro'), ('DELIVERED', 'Entregada'), ('CLOSED', 'Cerrada'), ('CANCELLED', 'Cancelada')], db_index=True, max_length=30, verbose_name='Estado destino'),
        ),
        migrations.AlterField(
            model_name='trabajofotocopia',
            name='tipo_uso',
            field=models.CharField(choices=[('INTERNO', 'Uso Institucional (Colegio)'), ('PERSONAL', 'Uso Personal (Docente)')], max_length=20, verbose_name='Tipo de Uso'),
        ),
    ]
