# Generated by Django 5.2.7 on 2025-11-11 09:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'tba_bodega_conf_categoria',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntregaBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad Entregada')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie del bien entregado', max_length=100, null=True, verbose_name='Número de Serie')),
                ('estado_fisico', models.CharField(blank=True, help_text='Estado físico del bien al momento de la entrega', max_length=50, null=True, verbose_name='Estado Físico')),
            ],
            options={
                'verbose_name': 'Detalle Entrega Bien',
                'verbose_name_plural': 'Detalles Entrega Bienes',
                'db_table': 'tba_bodega_entrega_bien_detalle',
                'ordering': ['entrega', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EntregaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número de Entrega')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('motivo', models.TextField(verbose_name='Motivo de la Entrega')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Entrega de Artículo',
                'verbose_name_plural': 'Entregas de Artículos',
                'db_table': 'tba_bodega_entrega_articulo',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='EntregaBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número de Entrega')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('motivo', models.TextField(verbose_name='Motivo de la Entrega')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Entrega de Bien/Activo',
                'verbose_name_plural': 'Entregas de Bienes/Activos',
                'db_table': 'tba_bodega_entrega_bien',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='EstadoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Color (Hex)')),
                ('es_inicial', models.BooleanField(default=False, verbose_name='Estado Inicial')),
                ('es_final', models.BooleanField(default=False, verbose_name='Estado Final')),
            ],
            options={
                'verbose_name': 'Estado de Entrega',
                'verbose_name_plural': 'Estados de Entrega',
                'db_table': 'tba_bodega_estado_entrega',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad')),
                ('operacion', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20, verbose_name='Operación')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('stock_antes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Antes')),
                ('stock_despues', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Después')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'tba_bodega_movimientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('requiere_autorizacion', models.BooleanField(default=False, verbose_name='Requiere Autorización')),
            ],
            options={
                'verbose_name': 'Tipo de Entrega',
                'verbose_name_plural': 'Tipos de Entrega',
                'db_table': 'tba_bodega_conf_tipoentrega',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimiento',
                'db_table': 'tba_bodega_conf_tipomovimiento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('simbolo', models.CharField(max_length=10, verbose_name='Símbolo')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'tba_bodega_unidad_medida',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodegas_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'tba_bodega_conf_bodega',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras del producto (dejar vacío para auto-generar)', max_length=100, null=True, unique=True, verbose_name='Código de Barras')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Máximo')),
                ('punto_reorden', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Punto de Reorden')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('marcas', models.ManyToManyField(blank=True, help_text='Marcas asociadas al artículo', related_name='articulos_bodega', to='activos.marca', verbose_name='Marcas')),
                ('ubicacion_fisica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='bodega.bodega', verbose_name='Ubicación Física (Bodega)')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='bodega.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'tba_bodega_articulos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntregaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad Entregada')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='bodega.articulo', verbose_name='Artículo')),
            ],
            options={
                'verbose_name': 'Detalle Entrega Artículo',
                'verbose_name_plural': 'Detalles Entrega Artículos',
                'db_table': 'tba_bodega_entrega_articulo_detalle',
                'ordering': ['entrega', 'id'],
            },
        ),
    ]
