# Generated by Django 5.2.7 on 2025-11-11 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0002_initial'),
        ('bodega', '0001_initial'),
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentregaarticulo',
            name='detalle_solicitud',
            field=models.ForeignKey(blank=True, help_text='Vincula con línea específica de solicitud (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_entregas', to='solicitudes.detallesolicitud', verbose_name='Detalle de Solicitud'),
        ),
        migrations.AddField(
            model_name='detalleentregabien',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_bienes', to='activos.activo', verbose_name='Activo/Bien'),
        ),
        migrations.AddField(
            model_name='entregaarticulo',
            name='bodega_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_articulos', to='bodega.bodega', verbose_name='Bodega de Origen'),
        ),
        migrations.AddField(
            model_name='entregaarticulo',
            name='departamento_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entregas', to='solicitudes.departamento', verbose_name='Departamento Destino'),
        ),
        migrations.AddField(
            model_name='entregaarticulo',
            name='entregado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entregadas_por', to=settings.AUTH_USER_MODEL, verbose_name='Entregado Por'),
        ),
        migrations.AddField(
            model_name='entregaarticulo',
            name='recibido_por',
            field=models.ForeignKey(help_text='Usuario que recibe la entrega', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_recibidas_por', to=settings.AUTH_USER_MODEL, verbose_name='Recibido Por'),
        ),
        migrations.AddField(
            model_name='entregaarticulo',
            name='solicitud',
            field=models.ForeignKey(blank=True, help_text='Solicitud de artículos asociada a esta entrega (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_articulos', to='solicitudes.solicitud', verbose_name='Solicitud Asociada'),
        ),
        migrations.AddField(
            model_name='detalleentregaarticulo',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bodega.entregaarticulo', verbose_name='Entrega'),
        ),
        migrations.AddField(
            model_name='entregabien',
            name='departamento_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entregas', to='solicitudes.departamento', verbose_name='Departamento Destino'),
        ),
        migrations.AddField(
            model_name='entregabien',
            name='entregado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entregadas_por', to=settings.AUTH_USER_MODEL, verbose_name='Entregado Por'),
        ),
        migrations.AddField(
            model_name='entregabien',
            name='recibido_por',
            field=models.ForeignKey(help_text='Usuario que recibe la entrega', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_recibidas_por', to=settings.AUTH_USER_MODEL, verbose_name='Recibido Por'),
        ),
        migrations.AddField(
            model_name='detalleentregabien',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bodega.entregabien', verbose_name='Entrega'),
        ),
        migrations.AddField(
            model_name='entregabien',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='bodega.estadoentrega', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='entregaarticulo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='bodega.estadoentrega', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='bodega.articulo', verbose_name='Artículo'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bodega', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='entregabien',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='bodega.tipoentrega', verbose_name='Tipo de Entrega'),
        ),
        migrations.AddField(
            model_name='entregaarticulo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='bodega.tipoentrega', verbose_name='Tipo de Entrega'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='bodega.tipomovimiento', verbose_name='Tipo de Movimiento'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidades_medida',
            field=models.ManyToManyField(help_text='Unidades de medida aplicables al artículo', related_name='articulos', to='bodega.unidadmedida', verbose_name='Unidades de Medida'),
        ),
    ]
