# Generated by Django 5.2.7 on 2025-11-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_initial'),
        ('bodega', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregaarticulo',
            options={'ordering': ['-fecha_entrega'], 'permissions': [('registrar_entrega_articulo', 'Puede registrar entrega de artículos'), ('aprobar_entrega_articulo', 'Puede aprobar entrega de artículos'), ('cancelar_entrega_articulo', 'Puede cancelar entrega de artículos'), ('ver_todas_entregas_articulos', 'Puede ver todas las entregas de artículos')], 'verbose_name': 'Entrega de Artículo', 'verbose_name_plural': 'Entregas de Artículos'},
        ),
        migrations.AlterModelOptions(
            name='entregabien',
            options={'ordering': ['-fecha_entrega'], 'permissions': [('registrar_entrega_bien', 'Puede registrar entrega de bienes'), ('aprobar_entrega_bien', 'Puede aprobar entrega de bienes'), ('cancelar_entrega_bien', 'Puede cancelar entrega de bienes'), ('ver_todas_entregas_bienes', 'Puede ver todas las entregas de bienes')], 'verbose_name': 'Entrega de Bien/Activo', 'verbose_name_plural': 'Entregas de Bienes/Activos'},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('registrar_entrada', 'Puede registrar entradas de inventario'), ('registrar_salida', 'Puede registrar salidas de inventario'), ('ajustar_stock', 'Puede realizar ajustes de stock'), ('ver_historial_movimientos', 'Puede ver historial de movimientos'), ('ver_reportes_inventario', 'Puede ver reportes de inventario')], 'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='marcas',
            field=models.ManyToManyField(blank=True, help_text='Marcas asociadas al artículo', related_name='articulos', to='activos.marca', verbose_name='Marcas'),
        ),
    ]
