# Generated by Django 5.2.7 on 2025-11-23 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_alter_entregaarticulo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='observaciones',
        ),
    ]
