# Generated by Django 5.2.7 on 2025-11-23 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_remove_categoria_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='unidades_medida',
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, help_text='Unidad de medida del artículo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='bodega.unidadmedida', verbose_name='Unidad de Medida'),
        ),
    ]
