# Generated by Django 5.2.7 on 2025-11-23 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_remove_articulo_unidades_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='punto_reorden',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Punto de Reorden'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock_actual',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock_maximo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Máximo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='stock_minimo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='detalleentregaarticulo',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Entregada'),
        ),
        migrations.AlterField(
            model_name='detalleentregabien',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Entregada'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='stock_antes',
            field=models.IntegerField(verbose_name='Stock Antes'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='stock_despues',
            field=models.IntegerField(verbose_name='Stock Después'),
        ),
    ]
