# Generated by Django 5.2.7 on 2025-11-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0006_alter_articulo_punto_reorden_and_more'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentregabien',
            name='detalle_solicitud',
            field=models.ForeignKey(blank=True, help_text='Vincula con línea específica de solicitud (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_entregas_bienes', to='solicitudes.detallesolicitud', verbose_name='Detalle de Solicitud'),
        ),
        migrations.AddField(
            model_name='entregabien',
            name='solicitud',
            field=models.ForeignKey(blank=True, help_text='Solicitud de activos asociada a esta entrega (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas_bienes', to='solicitudes.solicitud', verbose_name='Solicitud Asociada'),
        ),
    ]
