# Generated by Django 5.2.7 on 2025-11-25 20:24
# Modificado para incluir migración de datos

import django.db.models.deletion
from django.db import migrations, models


def migrar_operaciones_existentes(apps, schema_editor):
    """
    Migración de datos: Convierte los valores de texto 'ENTRADA'/'SALIDA'
    del campo operacion a ForeignKey del nuevo modelo Operacion.
    
    Esta función:
    1. Crea los registros iniciales de Operacion (ENTRADA y SALIDA)
    2. Para cada movimiento existente, asigna el ID correspondiente
    """
    Operacion = apps.get_model('bodega', 'Operacion')
    Movimiento = apps.get_model('bodega', 'Movimiento')
    
    # Crear operaciones base si no existen
    op_entrada, _ = Operacion.objects.get_or_create(
        codigo='ENT',
        defaults={
            'nombre': 'Entrada',
            'tipo': 'ENTRADA',
            'descripcion': 'Operación de entrada de artículos al inventario',
            'activo': True,
            'eliminado': False,
        }
    )
    op_salida, _ = Operacion.objects.get_or_create(
        codigo='SAL',
        defaults={
            'nombre': 'Salida',
            'tipo': 'SALIDA',
            'descripcion': 'Operación de salida de artículos del inventario',
            'activo': True,
            'eliminado': False,
        }
    )
    
    # Actualizar movimientos existentes
    # Nota: operacion_old contiene el valor de texto original
    for movimiento in Movimiento.objects.all():
        if hasattr(movimiento, 'operacion_old'):
            if movimiento.operacion_old == 'ENTRADA':
                movimiento.operacion = op_entrada
            else:
                movimiento.operacion = op_salida
            movimiento.save()


def revertir_migracion(apps, schema_editor):
    """
    Función de reversión: Convierte ForeignKey de vuelta a CharField
    """
    Movimiento = apps.get_model('bodega', 'Movimiento')
    
    for movimiento in Movimiento.objects.select_related('operacion').all():
        if movimiento.operacion:
            movimiento.operacion_old = movimiento.operacion.tipo
            movimiento.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0007_detalleentregabien_detalle_solicitud_and_more'),
    ]

    operations = [
        # Paso 1: Crear modelo Marca
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'tba_bodega_marca',
                'ordering': ['codigo'],
            },
        ),
        
        # Paso 2: Crear modelo Operacion
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], help_text='Define si la operación suma o resta del stock', max_length=20, verbose_name='Tipo de Operación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'db_table': 'tba_bodega_operacion',
                'ordering': ['codigo'],
            },
        ),
        
        # Paso 3: Remover campo marcas (ManyToMany antiguo)
        migrations.RemoveField(
            model_name='articulo',
            name='marcas',
        ),
        
        # Paso 4: Agregar campo marca (ForeignKey nuevo)
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(blank=True, help_text='Marca del artículo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='bodega.marca', verbose_name='Marca'),
        ),
        
        # Paso 5: Renombrar campo operacion a operacion_old para preservar datos
        migrations.RenameField(
            model_name='movimiento',
            old_name='operacion',
            new_name='operacion_old',
        ),
        
        # Paso 6: Agregar nuevo campo operacion como ForeignKey (nullable temporalmente)
        migrations.AddField(
            model_name='movimiento',
            name='operacion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text='Operación que determina si es entrada o salida', 
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='movimientos', 
                to='bodega.operacion', 
                verbose_name='Operación'
            ),
        ),
        
        # Paso 7: Migrar datos (convertir texto a ForeignKey)
        migrations.RunPython(migrar_operaciones_existentes, revertir_migracion),
        
        # Paso 8: Hacer el campo operacion NOT NULL
        migrations.AlterField(
            model_name='movimiento',
            name='operacion',
            field=models.ForeignKey(
                help_text='Operación que determina si es entrada o salida', 
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='movimientos', 
                to='bodega.operacion', 
                verbose_name='Operación'
            ),
        ),
        
        # Paso 9: Eliminar campo operacion_old
        migrations.RemoveField(
            model_name='movimiento',
            name='operacion_old',
        ),
    ]
