# Generated by Django 5.2.7 on 2025-12-07 00:56
# Modified to use existing renamed tables instead of creating new ones

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_movimientoactivo_estado_nuevo_and_more'),
        ('bodega', '0008_marca_operacion_remove_articulo_marcas_and_more'),
        ('compras', '0005_add_recepcion_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Las tablas ya existen (fueron renombradas desde compras)
        # Solo actualizamos el estado de Django sin tocar la BD
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Django cree que creó estos modelos
                migrations.CreateModel(
                    name='EstadoRecepcion',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                        ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                        ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                        ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                        ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                        ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                        ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                        ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Color (Hex)')),
                    ],
                    options={
                        'verbose_name': 'Estado de Recepción',
                        'verbose_name_plural': 'Estados de Recepción',
                        'db_table': 'tba_bodega_estado_recepcion',
                        'ordering': ['codigo'],
                    },
                ),
                migrations.CreateModel(
                    name='TipoRecepcion',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                        ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                        ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                        ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                        ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                        ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                        ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                        ('requiere_orden', models.BooleanField(default=False, verbose_name='Requiere Orden de Compra')),
                    ],
                    options={
                        'verbose_name': 'Tipo de Recepción',
                        'verbose_name_plural': 'Tipos de Recepción',
                        'db_table': 'tba_bodega_tipo_recepcion',
                        'ordering': ['codigo'],
                    },
                ),
                migrations.CreateModel(
                    name='RecepcionActivo',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                        ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                        ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                        ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                        ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número de Recepción')),
                        ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                        ('documento_referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento Referencia (Guía/Factura)')),
                        ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                        ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='bodega.estadorecepcion', verbose_name='Estado')),
                        ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='compras.ordencompra', verbose_name='Orden de Compra')),
                        ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibido Por')),
                        ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='bodega.tiporecepcion', verbose_name='Tipo de Recepción')),
                    ],
                    options={
                        'verbose_name': 'Recepción de Bien/Activo',
                        'verbose_name_plural': 'Recepciones de Bienes/Activos',
                        'db_table': 'tba_bodega_recepcion_activo',
                        'ordering': ['-fecha_recepcion'],
                        'permissions': [('registrar_recepcion_activo', 'Puede registrar recepción de activos'), ('aprobar_recepcion_activo', 'Puede aprobar recepción de activos'), ('rechazar_recepcion_activo', 'Puede rechazar recepción de activos'), ('ver_todas_recepciones_activos', 'Puede ver todas las recepciones de activos')],
                    },
                ),
                migrations.CreateModel(
                    name='DetalleRecepcionActivo',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                        ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                        ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                        ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Recibida')),
                        ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                        ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                        ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='activos.activo', verbose_name='Activo/Bien')),
                        ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bodega.recepcionactivo', verbose_name='Recepción')),
                    ],
                    options={
                        'verbose_name': 'Detalle Recepción Activo',
                        'verbose_name_plural': 'Detalles Recepción Activos',
                        'db_table': 'tba_bodega_recepcion_activo_detalle',
                        'ordering': ['recepcion', 'id'],
                    },
                ),
                migrations.CreateModel(
                    name='RecepcionArticulo',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                        ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                        ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                        ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                        ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número de Recepción')),
                        ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                        ('documento_referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento Referencia (Guía/Factura)')),
                        ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                        ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_articulos', to='bodega.bodega', verbose_name='Bodega')),
                        ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='bodega.estadorecepcion', verbose_name='Estado')),
                        ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='compras.ordencompra', verbose_name='Orden de Compra')),
                        ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibido Por')),
                        ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='bodega.tiporecepcion', verbose_name='Tipo de Recepción')),
                    ],
                    options={
                        'verbose_name': 'Recepción de Artículo',
                        'verbose_name_plural': 'Recepciones de Artículos',
                        'db_table': 'tba_bodega_recepcion_articulo',
                        'ordering': ['-fecha_recepcion'],
                        'permissions': [('registrar_recepcion_articulo', 'Puede registrar recepción de artículos'), ('aprobar_recepcion_articulo', 'Puede aprobar recepción de artículos'), ('rechazar_recepcion_articulo', 'Puede rechazar recepción de artículos'), ('ver_todas_recepciones_articulos', 'Puede ver todas las recepciones de artículos')],
                    },
                ),
                migrations.CreateModel(
                    name='DetalleRecepcionArticulo',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                        ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                        ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                        ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                        ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Recibida')),
                        ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                        ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                        ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                        ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='bodega.articulo', verbose_name='Artículo')),
                        ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bodega.recepcionarticulo', verbose_name='Recepción')),
                    ],
                    options={
                        'verbose_name': 'Detalle Recepción Artículo',
                        'verbose_name_plural': 'Detalles Recepción Artículos',
                        'db_table': 'tba_bodega_recepcion_articulo_detalle',
                        'ordering': ['recepcion', 'id'],
                    },
                ),
            ],
            database_operations=[
                # No hacer nada en la BD - las tablas ya existen (renombradas)
            ],
        ),
    ]
