# Generated by Django 5.2.7 on 2026-02-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0009_add_recepcion_models'),
        ('bodega', '0009_articulo_usuario_actualizacion_and_more'),
    ]

    operations = [
    ]
