# Generated by Django 5.2.7 on 2025-11-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadorecepcion',
            name='es_final',
        ),
        migrations.RemoveField(
            model_name='estadorecepcion',
            name='es_inicial',
        ),
    ]
