# Generated by Django 5.2.7 on 2025-11-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_remove_estadorecepcion_es_final_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha_orden', '-numero'], 'permissions': [('aprobar_ordencompra', 'Puede aprobar órdenes de compra'), ('rechazar_ordencompra', 'Puede rechazar órdenes de compra'), ('cerrar_ordencompra', 'Puede cerrar órdenes de compra'), ('anular_ordencompra', 'Puede anular órdenes de compra'), ('ver_todas_ordenescompra', 'Puede ver todas las órdenes de compra'), ('ver_reportes_compras', 'Puede ver reportes de compras')], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterModelOptions(
            name='recepcionactivo',
            options={'ordering': ['-fecha_recepcion'], 'permissions': [('registrar_recepcion_activo', 'Puede registrar recepción de activos'), ('aprobar_recepcion_activo', 'Puede aprobar recepción de activos'), ('rechazar_recepcion_activo', 'Puede rechazar recepción de activos'), ('ver_todas_recepciones_activos', 'Puede ver todas las recepciones de activos')], 'verbose_name': 'Recepción de Bien/Activo', 'verbose_name_plural': 'Recepciones de Bienes/Activos'},
        ),
        migrations.AlterModelOptions(
            name='recepcionarticulo',
            options={'ordering': ['-fecha_recepcion'], 'permissions': [('registrar_recepcion_articulo', 'Puede registrar recepción de artículos'), ('aprobar_recepcion_articulo', 'Puede aprobar recepción de artículos'), ('rechazar_recepcion_articulo', 'Puede rechazar recepción de artículos'), ('ver_todas_recepciones_articulos', 'Puede ver todas las recepciones de artículos')], 'verbose_name': 'Recepción de Artículo', 'verbose_name_plural': 'Recepciones de Artículos'},
        ),
    ]
