# Generated by Django 5.2.7 on 2025-11-24 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_ordencompra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='cantidad_recibida',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Recibida'),
        ),
        migrations.AlterField(
            model_name='detalleordencompraarticulo',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalleordencompraarticulo',
            name='cantidad_recibida',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Recibida'),
        ),
        migrations.AlterField(
            model_name='detallerecepcionactivo',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Recibida'),
        ),
        migrations.AlterField(
            model_name='detallerecepcionarticulo',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Recibida'),
        ),
    ]
