# Generated by Django 5.2.7 on 2025-12-07 00:56
# Modified to rename tables instead of deleting them, preserving data

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_detalleordencompra_cantidad_and_more'),
    ]

    operations = [
        # Renombrar tablas manteniendo datos
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Django ve que los modelos fueron eliminados de compras
                migrations.DeleteModel(name='DetalleRecepcionActivo'),
                migrations.DeleteModel(name='DetalleRecepcionArticulo'),
                migrations.DeleteModel(name='EstadoRecepcion'),
                migrations.DeleteModel(name='RecepcionActivo'),
                migrations.DeleteModel(name='RecepcionArticulo'),
                migrations.DeleteModel(name='TipoRecepcion'),
            ],
            database_operations=[
                # En BD real: renombrar tablas preservando datos
                migrations.RunSQL(
                    sql=[
                        "ALTER TABLE tba_compras_conf_estado_recepcion RENAME TO tba_bodega_estado_recepcion;",
                        "ALTER TABLE tba_compras_conf_tipo_recepcion RENAME TO tba_bodega_tipo_recepcion;",
                        "ALTER TABLE tba_compras_recepcion_articulo RENAME TO tba_bodega_recepcion_articulo;",
                        "ALTER TABLE tba_compras_recepcion_articulo_detalle RENAME TO tba_bodega_recepcion_articulo_detalle;",
                        "ALTER TABLE tba_compras_recepcion_activo RENAME TO tba_bodega_recepcion_activo;",
                        "ALTER TABLE tba_compras_recepcion_activo_detalle RENAME TO tba_bodega_recepcion_activo_detalle;",
                    ],
                    reverse_sql=[
                        "ALTER TABLE tba_bodega_estado_recepcion RENAME TO tba_compras_conf_estado_recepcion;",
                        "ALTER TABLE tba_bodega_tipo_recepcion RENAME TO tba_compras_conf_tipo_recepcion;",
                        "ALTER TABLE tba_bodega_recepcion_articulo RENAME TO tba_compras_recepcion_articulo;",
                        "ALTER TABLE tba_bodega_recepcion_articulo_detalle RENAME TO tba_compras_recepcion_articulo_detalle;",
                        "ALTER TABLE tba_bodega_recepcion_activo RENAME TO tba_compras_recepcion_activo;",
                        "ALTER TABLE tba_bodega_recepcion_activo_detalle RENAME TO tba_compras_recepcion_activo_detalle;",
                    ]
                ),
            ]
        ),
    ]
