# Generated by Django 5.2.7 on 2025-12-07 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_detalleordencompra_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='detalleordencompraarticulo',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='detalleordencompraarticulo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='detallerecepcionactivo',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='detallerecepcionactivo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='detallerecepcionarticulo',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='detallerecepcionarticulo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='estadoordencompra',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='estadoordencompra',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='estadorecepcion',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='estadorecepcion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='recepcionactivo',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='recepcionactivo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='recepcionarticulo',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='recepcionarticulo',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
        migrations.AddField(
            model_name='tiporecepcion',
            name='usuario_actualizacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Actualización'),
        ),
        migrations.AddField(
            model_name='tiporecepcion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Creación'),
        ),
    ]
