# Generated by Django 5.2.7 on 2025-11-11 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Motivo de Baja',
                'verbose_name_plural': 'Motivos de Baja',
                'db_table': 'tba_baja_motivo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='BajaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número de Baja')),
                ('fecha_baja', models.DateField(verbose_name='Fecha de Baja')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_baja', to='activos.activo', verbose_name='Activo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_inventario', to='activos.ubicacion', verbose_name='Ubicación de Baja')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas', to='bajas_inventario.motivobaja', verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Baja de Inventario',
                'verbose_name_plural': 'Bajas de Inventario',
                'db_table': 'tba_baja_inventario',
                'ordering': ['-fecha_baja', '-numero'],
                'permissions': [('registrar_baja', 'Puede registrar bajas de inventario'), ('aprobar_baja', 'Puede aprobar bajas de inventario'), ('ver_reportes_bajas', 'Puede ver reportes de bajas')],
            },
        ),
    ]
