# Generated by Django 5.2.7 on 2026-02-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajas_inventario', '0002_bajainventario_usuario_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajainventario',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='bajainventario',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='motivobaja',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='motivobaja',
            name='usuario_creacion',
        ),
    ]
