# Generated by Django 5.2.7 on 2025-11-11 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0002_initial'),
        ('bodega', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('modulo', models.CharField(choices=[('INVENTARIO', 'Inventario'), ('COMPRAS', 'Compras'), ('SOLICITUDES', 'Solicitudes'), ('MOVIMIENTOS', 'Movimientos'), ('BAJAS', 'Bajas'), ('GENERAL', 'General')], default='GENERAL', max_length=50, verbose_name='Módulo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipos de Reportes',
                'db_table': 'reporte_tipo',
                'ordering': ['modulo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio (Filtro)')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin (Filtro)')),
                ('parametros', models.JSONField(blank=True, help_text='Parámetros adicionales utilizados para generar el reporte', null=True, verbose_name='Parámetros')),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('HTML', 'HTML')], default='PDF', max_length=10, verbose_name='Formato')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/%Y/%m/', verbose_name='Archivo Generado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_generados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_generados', to='reportes.tiporeporte', verbose_name='Tipo de Reporte')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'db_table': 'reporte_generado',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Movimiento')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRASPASO', 'Traspaso'), ('AJUSTE', 'Ajuste Positivo'), ('AJUSTE_NEG', 'Ajuste Negativo'), ('BAJA', 'Baja')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Anterior')),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Nuevo')),
                ('documento_referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento de Referencia')),
                ('tipo_documento', models.CharField(blank=True, help_text='Ej: Orden de Compra, Solicitud, Baja, etc.', max_length=50, null=True, verbose_name='Tipo de Documento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='activos.activo', verbose_name='Activo')),
                ('bodega_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='bodega.bodega', verbose_name='Bodega Destino')),
                ('bodega_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='bodega.bodega', verbose_name='Bodega Origen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'reporte_movimiento_inventario',
                'ordering': ['-fecha_movimiento'],
                'indexes': [models.Index(fields=['-fecha_movimiento'], name='reporte_mov_fecha_m_a6ecfb_idx'), models.Index(fields=['activo', '-fecha_movimiento'], name='reporte_mov_activo__886ad5_idx'), models.Index(fields=['tipo_movimiento', '-fecha_movimiento'], name='reporte_mov_tipo_mo_0fd02d_idx')],
            },
        ),
    ]
