# Generated by Django 5.2.7 on 2026-02-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_movimientoinventario_usuario_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='reportegenerado',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='reportegenerado',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='tiporeporte',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='tiporeporte',
            name='usuario_creacion',
        ),
    ]
