# Generated by Django 5.2.7 on 2026-02-11 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Username usado en el intento (guardado incluso si falla)', max_length=150, verbose_name='Nombre de Usuario')),
                ('evento', models.CharField(choices=[('LOGIN_EXITOSO', 'Login Exitoso'), ('LOGIN_FALLIDO', 'Login Fallido'), ('LOGOUT', 'Logout'), ('CAMBIO_PASSWORD', 'Cambio de Contraseña'), ('RESETEO_PASSWORD', 'Reseteo de Contraseña'), ('SESION_EXPIRADA', 'Sesión Expirada')], db_index=True, help_text='Tipo de evento de sesión', max_length=20, verbose_name='Tipo de Evento')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Momento del evento', verbose_name='Fecha y Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del cliente', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente', null=True, verbose_name='User Agent')),
                ('exitoso', models.BooleanField(default=True, help_text='Indica si el evento fue exitoso', verbose_name='Exitoso')),
                ('razon_fallo', models.TextField(blank=True, help_text='Motivo del fallo si no fue exitoso', null=True, verbose_name='Razón de Fallo')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario asociado al evento de sesión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Sesión',
                'verbose_name_plural': 'Auditorías de Sesiones',
                'db_table': 'auditoria_sesion',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auditoria_s_timesta_971d99_idx'), models.Index(fields=['usuario', '-timestamp'], name='auditoria_s_usuario_281e4d_idx'), models.Index(fields=['username', '-timestamp'], name='auditoria_s_usernam_72cd04_idx'), models.Index(fields=['evento', '-timestamp'], name='auditoria_s_evento_43399e_idx'), models.Index(fields=['ip_address', '-timestamp'], name='auditoria_s_ip_addr_0c2ec2_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID del registro auditado', verbose_name='ID del Objeto')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('ACTIVAR', 'Activar'), ('DESACTIVAR', 'Desactivar'), ('RESTAURAR', 'Restaurar'), ('OTRO', 'Otro')], db_index=True, help_text='Tipo de acción realizada', max_length=20, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Momento en que se realizó la acción', verbose_name='Fecha y Hora')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado del objeto antes del cambio (formato JSON)', null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado del objeto después del cambio (formato JSON)', null=True, verbose_name='Datos Nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente utilizado', null=True, verbose_name='User Agent')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la acción', null=True, verbose_name='Descripción')),
                ('content_type', models.ForeignKey(help_text='Tipo de modelo auditado', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'auditoria_registro',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auditoria_r_timesta_3585a5_idx'), models.Index(fields=['content_type', 'object_id'], name='auditoria_r_content_8659d0_idx'), models.Index(fields=['usuario', '-timestamp'], name='auditoria_r_usuario_e57912_idx'), models.Index(fields=['accion', '-timestamp'], name='auditoria_r_accion_9738aa_idx')],
            },
        ),
    ]
